image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  GOPATH: /build
  REPO_NAME: github.com/Unity-Technologies/nemesis
  RUN_SRCCLR: 0

before_script:
  # Install CA certs, openssl to https downloads, python for gcloud sdk
  - apk add --update make ca-certificates openssl python
  - update-ca-certificates
  # Authorize the docker client with GCR
  - echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://gcr.io
  # Go to build directory

stages:
  - build

build:
  stage: build
  script:
    - |
      make build push
